### ISSUE TITLE
Cannot add or remove appliance to groups

### ISSUE THREAD

**Issue by tylerchayward** [ibm-datapower/appliance-management-center#6] opened 2015-10-22 13:20 UTC
I created a group for a pair of appliances, but the interface does not let me either add additional appliances or remove appliances from the group. 
In the former case, I cannot check the box next to my group in the Assign Groups window, in the second case I cannot uncheck the same box. Selecting one appliance in the group and one not in the group elicits the same behaviour. Regardless, the Apply button remains greyed out as well.
Also, is it possible to remove a group?
Nothing shows up in the catalina.out when I try to assign an appliance to a group.
Any help is appreciated!

**Comment by ghost** [comment] 2015-10-22 18:43
What browser are you using ? Can you look at the browser Javascript console to see if there are any errors?

**Comment by tylerchayward** [comment] 2015-10-23 11:05
Francisco,I have tried this in both Chrome and Firefox, no errors show up in either browser's JavaScript console. Actually, nothing shows up in the console when I click the check box. I have tried all three scenarios, add, remove, multiple appliances selected and they all return the same behaviour.Regards,
Tyler Courtney Hayward
Tel: +38516184831  | Mob: +385919065387 | E-mail: thayward@croz.net

---

CROZ d.o.o. | Lastovska 23 | 10000 Zagreb | Hrvatska | www.croz.net-----Francisco Moraes notifications@github.com wrote: -----To: ibm-datapower/appliance-management-center appliance-management-center@noreply.github.comFrom: Francisco Moraes notifications@github.comDate: 10/22/2015 08:43PMCc: tylerchayward thayward@croz.netSubject: Re: [appliance-management-center] Cannot add or remove appliance to groups (#6)What browser are you using ? Can you look at the browser Javascript console to see if there are any errors?

**Comment by ghost** [comment] 2015-10-23 15:09
The issue is now fixed by change 5207f7fe95541e5d0363566b959d8a0723fec0d6. Please let me know if you have any further issues.

**Closed as completed by ghost** 2015-10-23 15:09 UTC
Labels: bug
